dist: trusty
sudo: false
install: true
addons:
    apt:
        packages:
            - oracle-java8-installer
    sonarcloud:
        organization: "dmytro-bilokha-github"
language: java
jdk:
    - oraclejdk8
script:
  - mvn -Dsonar.jacoco.reportMissing.force.zero=true clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'